-- MySQL Script generated by MySQL Workbench
-- Thu Nov  4 23:37:27 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema luxuryDB
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS luxuryDB DEFAULT CHARACTER SET utf8 ;
USE luxuryDB ;


CREATE TABLE IF NOT EXISTS Customer (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `pass` VARCHAR(255) NOT NULL,
  `firstname` VARCHAR(255) NOT NULL,
  `lastname` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `phoneNumber` VARCHAR(45),
  `birthdate` DATE,
  `gender` CHAR NOT NULL,
  `street` VARCHAR(255) NOT NULL,
  `postalCode` INT NOT NULL,
  `locality` VARCHAR(255) NOT NULL,
  `country` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `username_uk` UNIQUE (`username`),
  CONSTRAINT `email_uk` UNIQUE (`email`)
)ENGINE = InnoDB;



CREATE TABLE IF NOT EXISTS Category (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS Product (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `price` DECIMAL(9,2) NOT NULL,
  `picture` BLOB NOT NULL,
  `Category_id` INT NOT NULL,
  PRIMARY KEY (`id`)
)ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `Language` (
  `code` VARCHAR(3) NOT NULL,
  `label` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `Order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `customer` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `order_customer_fk` FOREIGN KEY (`customer`) REFERENCES `Customer`(`id`)
)ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `luxuryDB`.`Coupon` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(255) NOT NULL,
  `value` DECIMAL(3,2) NOT NULL,
  `customer` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `coupon_customer_fk` FOREIGN KEY (`customer`) REFERENCES `Customer`(`id`)
)
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS OrderLine (
  `quantity` INT NOT NULL,
  `price` DECIMAL(4,2) NOT NULL,
  `product_id` INT NOT NULL,
  `order` INT NOT NULL,
  `product` INT NOT NULL,
  PRIMARY KEY (`product`, `order`),
  CONSTRAINT `orderLine_order_fk` FOREIGN KEY (`order`) REFERENCES `Order`(`id`),
  CONSTRAINT `orderLine_product_fk` FOREIGN KEY (`product`) REFERENCES `Product`(`id`)
)ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS Translation (
  `label` VARCHAR(255) NOT NULL,
  `category` INT NOT NULL,
  `language` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`category`, `language`),
  CONSTRAINT `translation_category_fk` FOREIGN KEY(`category`) REFERENCES `Category`(`id`),
  CONSTRAINT `translation_language_fk` FOREIGN KEY(`language`) REFERENCES `Language`(`code`)
)ENGINE = InnoDB;


INSERT INTO Customer (username, pass, firstname, lastname, email, phoneNumber, birthdate, gender, street, postalCode, locality, country) VALUES
('vially418', 'Jesuis123', 'Armel vially', 'Dongmo', 'armelvially418@icloud.com', '0492473290', str_to_date('10-10-2009', '%d-%m-%Y'), 'm', 'rue lucien namêche 39', 5000, 'namur', 'belgique');

select * from customer;